# Generated by Django 4.1.5 on 2023-01-27 09:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Farmer', '0002_farmerdata_uname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='farmerdata',
            old_name='name',
            new_name='fname',
        ),
        migrations.AddField(
            model_name='farmerdata',
            name='lname',
            field=models.CharField(default=django.utils.timezone.now, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='farmerdata',
            name='repassword',
            field=models.CharField(default='ENter', max_length=30),
        ),
    ]
