# Generated by Django 4.1.5 on 2023-01-27 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Farmer', '0003_rename_name_farmerdata_fname_farmerdata_lname_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farmerdata',
            name='repassword',
        ),
    ]
