# Generated by Django 4.1.5 on 2023-01-27 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Farmer', '0004_remove_farmerdata_repassword'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmerdata',
            name='place',
            field=models.CharField(default='HYD', max_length=20),
        ),
    ]
