# Generated by Django 4.1.5 on 2023-01-27 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Farmer', '0005_farmerdata_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmerdata',
            name='seller',
            field=models.BooleanField(default=False),
        ),
    ]
