# Generated by Django 4.1.5 on 2023-01-28 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Farmer', '0006_farmerdata_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerdata',
            name='products',
            field=models.CharField(default='none', max_length=50),
        ),
    ]
