# Generated by Django 4.1.5 on 2023-01-28 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Farmer', '0007_sellerdata_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerdata',
            name='uname',
            field=models.CharField(default='none', max_length=10),
        ),
    ]
