# Generated by Django 4.1.5 on 2023-01-27 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Laboratory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='labtable',
            name='email',
            field=models.CharField(default='abc@gmail.com', max_length=30),
        ),
        migrations.AddField(
            model_name='labtable',
            name='phone',
            field=models.CharField(default='9505486964', max_length=11),
        ),
    ]
