# Generated by Django 4.1.5 on 2023-01-27 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Laboratory', '0002_labtable_email_labtable_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='labtable',
            name='password',
            field=models.CharField(default='namehere', max_length=30),
        ),
    ]
