# Generated by Django 4.1.5 on 2023-01-27 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Laboratory', '0003_labtable_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('labid', models.CharField(max_length=10)),
                ('bookingdate', models.DateField()),
                ('phone', models.CharField(max_length=11)),
                ('address', models.TextField(max_length=100)),
            ],
        ),
    ]
