# Generated by Django 4.1.5 on 2023-01-27 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Laboratory', '0004_bookings'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='cusname',
            field=models.CharField(default='Ramu', max_length=60),
        ),
    ]
